import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('superfície de atendimento compartilhado', () => {
  it('mantém conexão administrativa finita com QR iniciado somente por Conectar', () => {
    const card = source('app/components/communication/InboxAdminCard.vue')
    const pairing = source('app/utils/communication-pairing.ts')
    const api = source('app/composables/api/createCommunicationApi.ts')
    expect(card).toContain('<UAlert')
    expect(card).toContain('effectiveStatus === \'CONNECTING\' && pairingCode')
    expect(card).toContain('label="Conectar"')
    expect(card).toContain('label="Desconectar"')
    expect(card).toContain('label="Remover credenciais"')
    expect(card).toContain('title="Remover credenciais desta sessão WhatsApp?"')
    expect(card).not.toContain('label="Logout"')
    expect(card).not.toContain('“Logout”')
    expect(card).toContain('label="Excluir sessão"')
    expect(card).toContain('&& enabled.value')
    expect(card).toContain('&& name.value.trim()')
    expect(card).toContain('connectBlockedReason')
    expect(card).toContain('Habilite o canal para usar “Conectar”.')
    expect(card).toContain('if (enabled.value && !props.inbox.is_enabled)')
    expect(card).toContain('const persisted = await persistSettings()')
    expect(card).toContain('<ShellConfirmModal')
    expect(card).toContain('Esta ação não pode ser desfeita')
    expect(card).toContain('histórico desta sessão')
    expect(card).not.toContain('Parear WhatsApp')
    expect(card).not.toContain('Revogar sessão')
    expect(card).not.toContain('Habilite e salve o canal antes de usar')
    expect(card).not.toContain('&& props.inbox.is_enabled')
    expect(card).toContain('pairingDeadlineAt')
    expect(card).toContain('stopSessionPolling')
    expect(card).toContain('if (current === null)')
    expect(card).toContain('await workspace.loadInboxes()')
    expect(card).toMatch(/async function deleteSession\(\) \{\s+stopSessionPolling\(\)/)
    expect(card).not.toContain('Date.now() + 120_000\n  if (expiresAt')
    expect(pairing).toContain('TERMINAL_PAIRING_EVENTS')
    expect(pairing).toContain('fallbackDeadline')
    expect(api).toContain('/session/connect')
    expect(api).toContain('/session/disconnect')
    expect(api).toContain('/session/logout')
    expect(api).toContain('method: \'DELETE\'')
  })

  it('segue o arquétipo master-detail com painel de contexto colapsável', () => {
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(page).toContain('communication-list-panel')
    expect(page).toContain('CommunicationTimelinePanel')
    expect(page).toContain('CommunicationContextPanel')
    expect(page).toContain('contextOpen')
    expect(page).toContain('toggleContext')
    expect(page).toContain('selectedConversation.value && contextOpen')
    expect(page).toContain('smaller(\'lg\')')
    expect(page).toContain('communication-mobile-timeline')
    expect(page).toContain('usesContextSlideover')
    expect(page).toContain('smaller(\'2xl\')')
    expect(page).toContain('communication-context-slideover')
    expect(page.match(/<USlideover/g)?.length).toBeGreaterThanOrEqual(2)
    expect(page).toContain('<ShellPageNavbar title="Atendimento">')
    expect(page).not.toContain('overflow-x-auto')
    expect(page).toMatch(/CommunicationContextPanel[\s\S]*class="hidden 2xl:flex"/)
    expect(page).not.toMatch(/CommunicationContextPanel[\s\S]*class="hidden (?:lg|xl):flex"/)
    expect(timeline).toContain('i-lucide-user')
    expect(timeline).toContain('communication-context-toggle')
    expect(timeline).toContain('toggleContext')
    expect(timeline).not.toContain('xl:hidden')
  })

  it('protege edição por teclado, restaura foco e oferece retry contextual', () => {
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')

    expect(page.match(/usingInput: false/g)).toHaveLength(2)
    for (const editable of [
      '\'input\'',
      '\'textarea\'',
      '\'select\'',
      '\'[role="combobox"]\'',
      '\'[contenteditable]:not([contenteditable="false"])\'',
      '\'[data-communication-composer]\''
    ]) {
      expect(page).toContain(editable)
    }
    expect(page).toContain('selectRelativeOutsideEditor')
    expect(page).toContain('isEditableShortcutTarget')
    expect(page).toContain('const conversationId = workspace.selectedConversationId.value')
    expect(page).toContain('conversationListRef.value?.focusConversation(conversationId)')
    expect(page.match(/label: 'Tentar novamente'/g)).toHaveLength(2)
    expect(page).toContain('onClick: () => workspace.initialize()')
    expect(page).toContain('onClick: () => workspace.synchronize()')

    expect(list).toContain('defineExpose({ focusConversation })')
    expect(list).toContain(':data-conversation-id="conversation.id"')
    expect(list).toContain(':id="`communication-conversation-${conversation.id}`"')
    expect(list).toContain('button.focus({ preventScroll: true })')
    expect(list).toContain('button.scrollIntoView({ block: \'nearest\' })')
  })

  it('oferece paginação incremental sem apagar estados válidos da fila', () => {
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')

    expect(page).toContain(':has-more="workspace.conversationsHasMore.value"')
    expect(page).toContain(':loading-more="workspace.conversationsLoadingMore.value"')
    expect(page).toContain(':load-more-error="workspace.conversationsLoadMoreError.value"')
    expect(page).toContain('@load-more="workspace.loadMoreConversations"')
    expect(page).toContain(':refreshing="workspace.conversationsRefreshing.value"')
    expect(page).toContain(':empty="workspace.conversationsEmpty.value"')

    expect(list).toContain('label="Carregar mais"')
    expect(list).toContain('communication-load-more')
    expect(list).toContain('communication-conversations-refreshing')
    expect(list).toContain('As conversas já carregadas permanecem disponíveis.')
    expect(list).toContain('label: \'Tentar novamente\'')
    expect(list).toContain('empty && !conversations.length')

    expect(workspace).toContain('COMMUNICATION_CONVERSATION_PAGE_SIZE = 50')
    expect(workspace).toContain('applyConversationMeta(response.meta)')
    expect(workspace).toContain('mergeCommunicationConversationPage')
    expect(workspace).toContain('isCommunicationConversationRequestCurrent')
    expect(workspace).toContain('conversationQueryController?.abort()')
    expect(workspace).not.toContain('...(selected && !visible.some')
  })

  it('usa cascas Shell nos overlays críticos do atendimento', () => {
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')

    expect(page).toContain('<ShellConfirmModal')
    expect(page).toContain('test-id="communication-purge-confirm"')
    expect(page).not.toMatch(/<UModal[\s>]/)
    expect(timeline).toContain('<ShellFormModal')
    expect(timeline).toContain('<ShellConfirmModal')
    expect(timeline).toContain('test-id="communication-edit-message"')
    expect(timeline).toContain('test-id="communication-revoke-message"')
    expect(timeline).not.toMatch(/<UModal[\s>]/)
  })

  it('composer cobre leitura, nota interna, canned response, citação e mídia privada', () => {
    const composer = source('app/components/communication/Composer.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(composer).toContain('Seu perfil possui acesso somente para leitura')
    expect(composer).toContain('props.unavailableReason')
    expect(composer).not.toContain('desativada por um dos switches de segurança')
    expect(composer).toContain('Nota interna')
    expect(composer).toContain('Resposta pronta')
    expect(composer).toContain('communication-composer-canned-touch')
    expect(composer).toContain('communication-composer-canned-listbox')
    expect(composer).toContain('renderCannedResponse')
    expect(composer).toContain('conversationId')
    expect(composer).toContain('compositionstart')
    expect(composer).toContain('replyToMessageId')
    expect(composer).toContain('type="file"')
    expect(timeline).toContain('<CommunicationComposer')
    expect(timeline).toContain(':conversation-id="conversation.id"')
    expect(timeline).toContain('Citar mensagem')
    expect(timeline).toContain('message.source === \'FISCAL_AUTOMATION\'')
    expect(timeline).toContain('media === \'AUDIO\'')
    expect(timeline).toContain('download')
    expect(timeline).not.toContain('<USkeleton')
    expect(composer).toContain('emit(\'presence\', \'COMPOSING\')')
    expect(composer).toContain('emit(\'presence\', \'PAUSED\')')
    expect(composer).toContain('emit(\'presence\', \'RECORDING\')')
    expect(composer).toContain('MediaRecorder')
    expect(composer).toContain('shouldSubmitCommunicationComposer')
    expect(composer).toContain('kind: file.value ? fileKind.value : \'TEXT\'')
    expect(composer).toContain('ptt: Boolean(file.value && ptt.value)')
    expect(composer).toContain('accept="image/webp,.webp"')
  })

  it('prefetch e cache efêmero evitam skeleton e corridas na troca de conversa', () => {
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(workspace).toContain('conversationDetails')
    expect(workspace).toContain('detailRequests')
    expect(workspace).toContain('selectionEpoch')
    expect(workspace).toContain('openingConversationId')
    expect(workspace).toContain('async function prefetchConversation')
    expect(workspace).toContain('if (epoch !== selectionEpoch) return false')
    expect(workspace).toContain('conversationDetails.value = {}')
    expect(workspace).toContain('async function refreshConversationDetail')
    expect(workspace).toContain('await refreshConversationDetail(selectedId, { reportError: false })')
    expect(page).toContain(':opening-id="workspace.openingConversationId.value"')
    expect(page).toContain('@prefetch="prefetchConversation"')
    expect(list).toContain('@pointerenter="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain('@pointerdown="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain('@focus="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain(':aria-busy="openingId === conversation.id"')
    expect(list).not.toContain('<USkeleton')
    expect(timeline).not.toContain('<USkeleton')
  })

  it('acompanha o fim condicionalmente e anuncia mensagens pendentes', () => {
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(timeline).toContain('appendedCommunicationMessages')
    expect(timeline).toContain('shouldFollowCommunicationTimeline')
    expect(timeline).toContain('followingLatest')
    expect(timeline).toContain('pendingNewMessages')
    expect(timeline).toContain('ResizeObserver')
    expect(timeline).toContain('@scroll.passive="handleMessagesScroll"')
    expect(timeline).toContain('communication-new-messages')
    expect(timeline).toContain('Ir para as mensagens mais recentes')
    expect(timeline).toContain('usePreferredReducedMotion')
  })

  it('representa tipos 1x1 e expõe somente ações tipadas do backend', () => {
    const content = source('app/components/communication/MessageContent.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const api = source('app/composables/api/createCommunicationApi.ts')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    for (const kind of ['LOCATION', 'CONTACT', 'POLL', 'INTERACTIVE', 'STICKER']) {
      expect(content).toContain(`message.kind === '${kind}'`)
    }
    expect(content).toContain('message.metadata?.revoked')
    expect(content).toContain('attachment.preview_url')
    expect(content).toContain('<audio')
    expect(content).toContain('<video')
    expect(content).toContain('markAudioPlayed')
    expect(timeline).toContain('message.metadata?.reactions')
    expect(timeline).toContain('COMMUNICATION_REACTION_EMOJIS')
    expect(timeline).toContain('scrollToMessage')
    expect(timeline).toContain('Editar mensagem')
    expect(timeline).toContain('Apagar para todos')
    expect(api).toContain('/messages/${messageId}/edit')
    expect(api).toContain('/messages/${messageId}/reaction')
    expect(api).toContain('/messages/${messageId}/poll-votes')
    expect(workspace).toContain('isCommunicationEphemeralEvent')
    expect(workspace).toContain('signalTimers')
    expect(workspace).toContain('const durable = incoming.filter')
  })

  it('mantém bolhas compactas, responsivas e acessíveis na timeline', () => {
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const content = source('app/components/communication/MessageContent.vue')
    expect(timeline).toContain('communication-message-bubble')
    expect(timeline).toContain('inline-block w-fit max-w-full')
    expect(timeline).toContain('max-w-[92%] sm:max-w-[78%] lg:max-w-[72%]')
    expect(timeline).toContain('\'rounded-br-md bg-primary/20 text-highlighted ring-primary/15\'')
    expect(timeline).toContain('\'-right-1 border-primary/15 bg-primary/20\'')
    expect(timeline).not.toContain('\'rounded-br-md bg-primary text-inverted ring-primary/30\'')
    expect(timeline).toContain('border-l-2 border-primary bg-default/50')
    expect(timeline).not.toContain('border-l-2 border-current')
    expect(timeline).toContain('\'rounded-bl-md bg-default text-highlighted ring-default\'')
    expect(timeline).toContain('\'rounded-bl-md bg-warning/10 text-highlighted ring-warning/40\'')
    expect(timeline).toContain('aria-hidden="true"')
    expect(timeline).toContain('Nota interna')
    expect(timeline).toContain('Enviada · WhatsApp')
    expect(timeline).toContain('Recebida · WhatsApp')
    expect(timeline).toContain('communication-message-meta')
    expect(timeline).toContain('<time :datetime="message.occurred_at || undefined">')
    expect(timeline).toContain('group-focus-within/message:opacity-100')
    expect(timeline).toContain('[@media(hover:hover)]:opacity-0')
    expect(timeline).toContain('aria-label="Reagir à mensagem"')
    expect(timeline).toContain('aria-label="Ações da mensagem"')
    expect(content).toContain('class="block w-full max-w-full px-2 py-2"')
    expect(content).not.toContain('min-w-56')
  })

  it('prioriza a identidade fiscal e mantém contato e telefone como contexto', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(list).toContain('communicationDisplayName(conversation)')
    expect(list).toContain('communicationContactLabel(conversation)')
    expect(timeline).toContain(':title="communicationDisplayName(conversation)"')
    expect(timeline).toContain('communicationContactLabel(conversation)')
  })

  it('evidencia a última imagem recebida sem depender apenas da miniatura', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const communication = source('app/utils/communication.ts')
    const types = source('app/types/communication.ts')
    expect(types).toContain('last_message?: CommunicationMessage | null')
    expect(communication).toContain('communicationConversationImageEvidence')
    expect(communication).toContain('message.direction !== \'INBOUND\'')
    expect(communication).toContain('message.kind !== \'IMAGE\'')
    expect(communication).toContain('!item.purged_at')
    expect(list).toContain('communication-conversation-image-evidence')
    expect(list).toContain('Imagem recebida')
    expect(list).toContain('Prévia indisponível')
    expect(list).toContain('Prévia da imagem recebida de')
    expect(list).toContain('loading="lazy"')
    expect(list).toContain('object-cover')
    expect(list).toContain('bg-elevated/60')
    expect(list).toContain('failedImagePreviewIds')
    expect(list).toContain('@error="markImagePreviewUnavailable(imageEvidence.messageId)"')
  })

  it('contexto cobre fila, responsável, snooze, labels, clientes e expurgo', () => {
    const context = source('app/components/communication/ContextPanel.vue')
    expect(context).toContain('Responsável')
    expect(context).toContain('Fila / departamento')
    expect(context).toContain('Adiar conversa')
    expect(context).toContain('Marcadores')
    expect(context).toContain('Clientes vinculados')
    expect(context).toContain('Exportar contato')
    expect(context).toContain('Expurgar dados')
    expect(context).toContain('Mensagens temporárias')
    expect(context).toContain('signals?.contact?.available')
    expect(context).toContain('communication-context-close')
    expect(context).toContain('resizable')
  })

  it('administra switches, inbox, QR, membros, políticas e destinatários sem egress externo', () => {
    const admin = source('app/components/communication/AdministrationSlideover.vue')
    const inbox = source('app/components/communication/InboxAdminCard.vue')
    const policy = source('app/components/communication/AutomationPolicyCard.vue')
    const recipients = source('app/components/communication/RecipientConfigurationPanel.vue')
    expect(admin).toContain('defaults permanecem fail-closed')
    expect(admin).toContain('CommunicationInboxAdminCard')
    expect(admin).toContain('CommunicationAutomationPolicyCard')
    expect(admin).toContain('CommunicationRecipientConfigurationPanel')
    expect(inbox).toContain('QRCode.toDataURL')
    expect(inbox).toContain('Membros autorizados')
    expect(inbox).toContain('communicationSessionActions')
    expect(inbox).toContain('Ambiente com comunicação desativada')
    expect(inbox).toContain('Gateway do WhatsApp desativado')
    expect(inbox).toContain('Comunicação do escritório desativada')
    expect(inbox).toContain('Canal desativado')
    expect(inbox).toContain('Habilite o canal para usar “Conectar”.')
    expect(inbox).toContain('persistSettings')
    expect(policy).toContain('SKIPPED_NO_DOCUMENT')
    expect(policy).toContain('Inbox geral')
    expect(recipients).toContain('SELECTED')
    expect(inbox).not.toMatch(/https?:\/\//)
  })

  it('integra REST tenant-scoped e navegação permission-aware', () => {
    const api = source('app/composables/api/createCommunicationApi.ts')
    const navigation = source('app/utils/navigation.ts')
    const routes = source('app/utils/communication-routes.ts')
    expect(api).toContain('const base = \'/api/v1/communication\'')
    expect(api).toContain('/automation-recipients')
    expect(api).toContain('/events')
    expect(api).toContain('FormData')
    expect(navigation).toContain('id: \'communication\'')
    expect(navigation).toContain('COMMUNICATION_INDEX_PATH')
    expect(navigation).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(navigation).toContain('type: \'trigger\'')
    expect(navigation).toContain('canViewCommunication(user)')
    expect(routes).toContain('conversations/${id}')
    expect(routes).toContain('communicationConversationPath')
    expect(routes).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(source('app/pages/communication/index.vue')).toContain('CommunicationWorkspacePage')
    expect(source('app/pages/communication/conversations/[id].vue')).toContain('CommunicationWorkspacePage')
    expect(source('app/components/communication/quick-responses/CatalogTable.vue')).toContain('ShellDataTable')
    expect(source('app/components/communication/CatalogAdminPanel.vue')).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(source('app/components/communication/CatalogAdminPanel.vue')).not.toContain('createCanned')
  })
})
