import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { resolveApiUrl } from '../../app/utils/api-url'

const root = (...parts: string[]) => resolve(process.cwd(), ...parts)
const read = (...parts: string[]) => readFileSync(root(...parts), 'utf8')

describe('communication shared content e iniciação outbound', () => {
  it('módulo SharedContent cobre teaser, galeria, viewer e jump autenticado', () => {
    const shared = read('app/components/communication/SharedContent.vue')
    const viewer = read('app/components/communication/MediaViewer.vue')
    const context = read('app/components/communication/ContextPanel.vue')
    const contactContext = read('app/components/communication/contacts/Context.vue')
    const api = read('app/composables/api/createCommunicationApi.ts')
    const types = read('app/types/communication/shared-content.ts')

    expect(shared).toContain('data-testid="communication-shared-content"')
    expect(shared).toContain('category = ref<SharedContentCategory>(\'media\')')
    expect(shared).toContain('label: \'Mídias\'')
    expect(shared).toContain('label: \'Links\'')
    expect(shared).toContain('label: \'Documentos\'')
    expect(shared).toContain('sharedContent(conversationId, params)')
    expect(shared).toContain('sharedContent(contactId!, params)')
    expect(shared).toContain('label="Ver tudo"')
    expect(shared).toContain('label="Carregar mais"')
    expect(shared).toContain('label="Tentar novamente"')
    expect(shared).toContain('Nenhum item visível nesta categoria.')
    expect(shared).toContain('aria-label="Ir para mensagem"')
    expect(shared).toContain('emit(\'jump\'')
    expect(shared).toContain('download.download')
    expect(shared).toContain('import { resolveApiUrl } from \'~/utils/api-url\'')
    expect(shared).toContain('function mediaUrl')
    expect(shared).toContain('resolveApiUrl(url, apiBase)')
    expect(shared).toContain('viewerOpen')
    expect(shared).toContain('CommunicationMediaViewer')
    expect(viewer).toContain('zoom')
    expect(viewer).toContain('rotation')
    expect(viewer).toContain('ArrowLeft')
    expect(viewer).toContain('ArrowRight')
    expect(viewer).toContain('aria-label="Mídia anterior"')
    expect(viewer).toContain('aria-label="Próxima mídia"')
    expect(shared).not.toContain('object_id')
    expect(shared).not.toContain('storage_context')

    expect(context).toContain('CommunicationSharedContent')
    expect(contactContext).toContain('CommunicationSharedContent')
    expect(api).toContain('`${base}/contacts/${contactId}/shared-content`')
    expect(api).toContain('`${base}/conversations/${id}/shared-content`')
    expect(types).toContain('export type SharedContentCategory = \'media\' | \'links\' | \'documents\'')
  })

  it('NewConversationModal aplica gates reais de reply, capability e multipart', () => {
    const modal = read('app/components/communication/NewConversationModal.vue')
    const catalog = read('app/components/communication/contacts/Catalog.vue')
    const detail = read('app/pages/communication/contacts/[id].vue')
    const workspace = read('app/components/communication/WorkspacePage.vue')
    const api = read('app/composables/api/createCommunicationApi.ts')

    expect(modal).toContain('canReply')
    expect(modal).toContain('conversation_initiation.enabled')
    expect(modal).toContain('outboundCapabilities()')
    expect(modal).toContain('tenant_not_allowlisted')
    expect(modal).toContain('kill_switch_active')
    expect(modal).toContain('permission_denied')
    expect(modal).toContain('rollout_disabled')
    expect(modal).toContain('conversations.create')
    expect(modal).toContain('idempotencyKey')
    expect(modal).toContain('crypto.randomUUID()')
    expect(modal).toContain('kindForFile')
    expect(modal).toContain('inbox.is_enabled && inbox.status === \'CONNECTED\'')
    expect(modal).toContain('availableInboxes.value.find(inbox => inbox.is_default)')
    expect(modal).toContain('const selectedInbox = computed')
    expect(modal).toContain('inboxes.some(inbox => inbox.id === inboxId.value)')
    expect(modal).toContain('api.communication.contacts.list({')
    expect(modal).toContain('per_page: 20')
    expect(modal).toContain('data-testid="communication-new-conversation-contact-search"')
    expect(modal).toContain('data-testid="communication-new-conversation-load-more"')
    expect(modal).toContain('return \'IMAGE\'')
    expect(modal).toContain('return \'AUDIO\'')
    expect(modal).toContain('return \'VIDEO\'')
    expect(modal).toContain('return \'DOCUMENT\'')
    expect(modal).toContain('ptt')
    expect(modal).toContain('file.value')
    expect(modal).toContain('communication.reply')

    expect(catalog).toContain('CommunicationNewConversationModal')
    expect(detail).toContain('CommunicationNewConversationModal')
    expect(workspace).toContain('CommunicationNewConversationModal')
    expect(api).toContain('create: (body: {')
    expect(api).toContain('Idempotency-Key')
  })

  it('normaliza mídia e avatares pelo proxy Sanctum sem alterar URLs absolutas', () => {
    const list = read('app/components/communication/ConversationList.vue')
    const timeline = read('app/components/communication/TimelinePanel.vue')
    const messageContent = read('app/components/communication/MessageContent.vue')
    const profile = read('app/components/communication/contacts/ProfileSection.vue')
    expect(resolveApiUrl('/api/v1/communication/attachments/1/preview', '/api/sanctum'))
      .toBe('/api/sanctum/api/v1/communication/attachments/1/preview')
    expect(resolveApiUrl('https://cdn.example.test/avatar.jpg', '/api/sanctum'))
      .toBe('https://cdn.example.test/avatar.jpg')
    expect(list).toContain('<CommunicationProfileAvatar')
    expect(list).toContain(':subject="conversation.contact"')
    expect(timeline).toContain('communicationProfilePictureSrc(conversation.contact, apiBase)')
    expect(messageContent).toContain('import { resolveApiUrl } from \'~/utils/api-url\'')
    expect(messageContent).toContain('resolveApiUrl(url, apiBase)')
    expect(messageContent).toContain(':src="mediaUrl(stickerAttachment.preview_url)"')
    expect(messageContent).toContain(':src="mediaUrl(attachment.preview_url)"')
    expect(profile).toContain('<CommunicationProfileAvatar')
    expect(profile).toContain(':subject="contact"')
  })

  it('deep-link de mensagem ancora a timeline e destaca a origem', () => {
    const workspace = read('app/components/communication/WorkspacePage.vue')
    const timeline = read('app/components/communication/TimelinePanel.vue')
    const composable = read('app/composables/useCommunicationWorkspace.ts')
    const api = read('app/composables/api/createCommunicationApi.ts')
    const detail = read('app/pages/communication/contacts/[id].vue')
    const messageRoute = read('app/pages/communication/conversations/[id]/messages/[messageId].vue')

    expect(workspace).toContain('route.params.messageId')
    expect(workspace).toContain('selectConversationAtMessage')
    expect(workspace).toContain('highlighted-message-id')
    expect(workspace).toContain('communicationConversationMessagePath(input.conversationId, input.messageId)')
    expect(timeline).toContain('highlightedMessageId')
    expect(timeline).toContain('scrollToMessage')
    expect(composable).toContain('selectConversationAtMessage')
    expect(composable).toContain('const anchor = messageId ? \'message\'')
    expect(composable).toContain('message_id: messageId')
    expect(api).toContain('anchor?: \'latest\' | \'first_unread\' | \'message\'')
    expect(api).toContain('message_id?: number')
    expect(detail).toContain('communicationConversationMessagePath(input.conversationId, input.messageId)')
    expect(messageRoute).toContain('parsePositiveRouteId(to.params.messageId)')
    expect(messageRoute).toContain('definePageMeta')
    expect(messageRoute).not.toContain('route.query')
  })
})
