import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('superfície de atendimento compartilhado', () => {
  it('mantém conexão administrativa finita com QR iniciado somente por Conectar', () => {
    const card = source('app/components/communication/InboxAdminCard.vue')
    const pairing = source('app/utils/communication-pairing.ts')
    const api = source('app/composables/api/createCommunicationApi.ts')
    expect(card).toContain('<UAlert')
    expect(card).toContain('effectiveStatus === \'CONNECTING\' && pairingCode')
    expect(card).toContain('label="Conectar"')
    expect(card).toContain('label="Desconectar"')
    expect(card).toContain('label="Remover credenciais"')
    expect(card).toContain('title="Remover credenciais desta sessão WhatsApp?"')
    expect(card).not.toContain('label="Logout"')
    expect(card).not.toContain('“Logout”')
    expect(card).toContain('label="Excluir sessão"')
    expect(card).toContain('&& enabled.value')
    expect(card).toContain('&& name.value.trim()')
    expect(card).toContain('connectBlockedReason')
    expect(card).toContain('Habilite o canal para usar “Conectar”.')
    expect(card).toContain('if (enabled.value && !props.inbox.is_enabled)')
    expect(card).toContain('const persisted = await persistSettings()')
    expect(card).toContain('<ShellConfirmModal')
    expect(card).toContain('Esta ação não pode ser desfeita')
    expect(card).toContain('histórico desta sessão')
    expect(card).not.toContain('Parear WhatsApp')
    expect(card).not.toContain('Revogar sessão')
    expect(card).not.toContain('Habilite e salve o canal antes de usar')
    expect(card).not.toContain('&& props.inbox.is_enabled')
    expect(card).toContain('pairingDeadlineAt')
    expect(card).toContain('stopSessionPolling')
    expect(card).toContain('if (current === null)')
    expect(card).toContain('await workspace.loadInboxes()')
    expect(card).toMatch(/async function deleteSession\(\) \{\s+stopSessionPolling\(\)/)
    expect(card).not.toContain('Date.now() + 120_000\n  if (expiresAt')
    expect(pairing).toContain('TERMINAL_PAIRING_EVENTS')
    expect(pairing).toContain('fallbackDeadline')
    expect(api).toContain('/session/connect')
    expect(api).toContain('/session/disconnect')
    expect(api).toContain('/session/logout')
    expect(api).toContain('method: \'DELETE\'')
  })

  it('segue o arquétipo master-detail com painel de contexto colapsável', () => {
    const page = source('app/components/communication/WorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(page).toContain('communication-list-panel')
    expect(page).toContain('CommunicationTimelinePanel')
    expect(page).toContain('CommunicationContextPanel')
    expect(page).toContain('contextOpen')
    expect(page).toContain('toggleContext')
    expect(page).toContain('selectedConversation.value && contextOpen')
    expect(page).toContain('smaller(\'lg\')')
    expect(page).toContain('communication-mobile-timeline')
    expect(page).toContain('usesContextSlideover')
    expect(page).toContain('smaller(\'2xl\')')
    expect(page).toContain('communication-context-slideover')
    expect(page.match(/<USlideover/g)?.length).toBeGreaterThanOrEqual(2)
    expect(page).toContain('<ShellPageNavbar title="Atendimento">')
    expect(page).not.toContain('overflow-x-auto')
    expect(page).toMatch(/CommunicationContextPanel[\s\S]*class="hidden 2xl:flex"/)
    expect(page).not.toMatch(/CommunicationContextPanel[\s\S]*class="hidden (?:lg|xl):flex"/)
    expect(timeline).toContain('i-lucide-panel-right-open')
    expect(timeline).toContain('i-lucide-panel-right-close')
    expect(timeline).toContain('communication-context-toggle')
    expect(timeline).toContain('toggleContext')
    expect(timeline).not.toContain('xl:hidden')
  })

  it('renderiza fotos autorizadas com fallback e seleção central acessível', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const context = source('app/components/communication/ContextPanel.vue')
    const catalog = source('app/components/communication/contacts/CatalogTable.vue')
    const profile = source('app/components/communication/contacts/ProfileSection.vue')
    const types = source('app/types/communication/contacts.ts')
    const generatedTypes = source('app/types/generated/public-api.ts')

    expect(types.match(/profile_picture_url\?: string \| null/g)).toHaveLength(2)
    expect(types).toContain('= \'UNKNOWN\' | \'PENDING\' | \'READY\' | \'UNAVAILABLE\' | \'FAILED\'')
    expect(generatedTypes.match(/profile_picture_url[^\n]*string \| null/g)?.length).toBeGreaterThanOrEqual(2)
    for (const conversationSurface of [list, timeline, context]) {
      expect(conversationSurface).toContain('communicationProfilePictureSrc(conversation.contact, apiBase)')
      expect(conversationSurface).toContain(':alt="communicationDisplayName(conversation)"')
      expect(conversationSurface).not.toContain(':text="communicationDisplayName(conversation)"')
    }
    expect(timeline).not.toMatch(/<UAvatar\s+v-else/)
    expect(catalog).toContain('communicationProfilePictureSrc(contact, apiBase)')
    expect(catalog).toContain(':text="communicationContactInitials(contact)"')
    expect(catalog).toContain('size-[42px] shrink-0 rounded-lg')
    expect(catalog).toContain(':data-testid="`communication-contact-avatar-${contact.id}`"')
    expect(profile).toContain('communicationProfilePictureSrc(contact, apiBase)')
    expect(profile).toContain(':text="communicationContactInitials(contact)"')
    expect(profile).toContain('size-[42px] shrink-0 rounded-lg')
    expect(profile).toContain('root: \'rounded-lg\'')
    expect(profile).toContain('data-testid="communication-contact-profile-avatar"')

    expect(list).toContain('class="group/avatar relative size-8 shrink-0"')
    expect(list).toContain('absolute inset-0 z-10 flex items-center justify-center rounded-full')
    expect(list).not.toContain('-bottom-1 -end-1')
    expect(list).toContain('group-hover/avatar:opacity-100')
    expect(list).toContain('group-hover/avatar:pointer-events-auto')
    expect(list).toContain('group-focus-within/row:opacity-100')
    expect(list).toContain('group-focus-within/row:pointer-events-auto')
    expect(list).toContain('communication-conversation-avatar-select-')
    expect(list).toContain('[@media(pointer:coarse)]:opacity-100')
    expect(list).toContain('[@media(pointer:coarse)]:pointer-events-auto')
    expect(list).toContain('pointer-events-auto')
    expect(list).toContain('bg-default/75')
    expect(list).toContain('opacity-100')
    expect(list).toContain('@click.stop')
    expect(list).toContain('@keydown.enter.stop.prevent')
    expect(list).toContain('@keydown.space.stop')
  })

  it('protege edição por teclado, restaura foco e oferece retry contextual', () => {
    const page = source('app/components/communication/WorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')

    expect(page.match(/usingInput: false/g)).toHaveLength(2)
    for (const editable of [
      '\'input\'',
      '\'textarea\'',
      '\'select\'',
      '\'[role="combobox"]\'',
      '\'[contenteditable]:not([contenteditable="false"])\'',
      '\'[data-communication-composer]\''
    ]) {
      expect(page).toContain(editable)
    }
    expect(page).toContain('selectRelativeOutsideEditor')
    expect(page).toContain('isEditableShortcutTarget')
    expect(page).toContain('const conversationId = workspace.selectedConversationId.value')
    expect(page).toContain('conversationListRef.value?.focusConversation(conversationId)')
    expect(page.match(/label: 'Tentar novamente'/g)).toHaveLength(2)
    expect(page).toContain('onClick: () => workspace.initialize()')
    expect(page).toContain('onClick: () => workspace.synchronize()')

    expect(list).toContain('defineExpose({ focusConversation, focusList })')
    expect(list).toContain(':data-conversation-id="conversation.id"')
    expect(list).toContain(':id="`communication-conversation-${conversation.id}`"')
    expect(list).toContain('button.focus({ preventScroll: true })')
    expect(list).toContain('button.scrollIntoView({ block: \'nearest\' })')
    // Checkbox, abertura e menu são irmãos (sem interativos aninhados).
    expect(list).toContain('UCheckbox')
    expect(list).toContain('CommunicationConversationActions')
    expect(list).not.toContain('communication-select-loaded')
    expect(list).not.toContain('toggle-select-all')
    expect(list).toContain('tabindex="-1"')
    expect(list).toContain('focusList')
    expect(list).toContain('ShellInfiniteTableLoader')
    expect(list).toContain('communication-conversation-virtual')
  })

  it('oferece paginação incremental sem apagar estados válidos da fila', () => {
    const page = source('app/components/communication/WorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')

    expect(page).toContain(':has-more="workspace.conversationsHasMore.value"')
    expect(page).toContain(':loading-more="workspace.conversationsLoadingMore.value"')
    expect(page).toContain(':load-more-error="workspace.conversationsLoadMoreError.value"')
    expect(page).toContain('@load-more="workspace.loadMoreConversations"')
    expect(page).toContain(':empty="workspace.conversationsEmpty.value"')
    expect(page).not.toContain(':refreshing="workspace.conversationsRefreshing.value"')

    expect(list).toContain('label="Carregar mais"')
    expect(list).toContain('communication-load-more')
    expect(list).toContain('communication-conversations-skeleton')
    expect(list).not.toContain('Atualizando conversas')
    expect(list).not.toContain('communication-conversations-refreshing')
    expect(list).toContain('As conversas já carregadas permanecem disponíveis.')
    expect(list).toContain('label: \'Tentar novamente\'')
    expect(list).toContain('empty && !conversations.length')

    expect(workspace).toContain('COMMUNICATION_CONVERSATION_PAGE_SIZE = 50')
    expect(workspace).toContain('applyConversationMeta(response.meta)')
    expect(workspace).toContain('mergeCommunicationConversationPage')
    expect(workspace).toContain('isConversationRequestCurrent')
    expect(workspace).toContain('conversationQueryController?.abort()')
    expect(workspace).not.toContain('...(selected && !visible.some')
  })

  it('usa cascas Shell nos overlays críticos do atendimento', () => {
    const page = source('app/components/communication/WorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')

    expect(page).toContain('<ShellConfirmModal')
    expect(page).toContain('test-id="communication-purge-confirm"')
    expect(page).not.toMatch(/<UModal[\s>]/)
    expect(timeline).toContain('<ShellFormModal')
    expect(timeline).toContain('<ShellConfirmModal')
    expect(timeline).toContain('test-id="communication-edit-message"')
    expect(timeline).toContain('test-id="communication-revoke-message"')
    expect(timeline).not.toMatch(/<UModal[\s>]/)
  })

  it('composer cobre leitura, nota interna, canned response, citação e mídia privada', () => {
    const composer = source('app/components/communication/Composer.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(composer).toContain('Seu perfil possui acesso somente para leitura')
    expect(composer).toContain('props.unavailableReason')
    expect(composer).not.toContain('desativada por um dos switches de segurança')
    expect(composer).toContain('Nota interna')
    expect(composer).toContain('Resposta pronta')
    expect(composer).toContain('communication-composer-canned-touch')
    expect(composer).toContain('communication-composer-canned-listbox')
    expect(composer).toContain('renderCannedResponse')
    expect(composer).toContain('conversationId')
    expect(composer).toContain('compositionstart')
    expect(composer).toContain('replyToMessageId')
    expect(composer).toContain('type="file"')
    expect(timeline).toContain('<CommunicationComposer')
    expect(timeline).toContain(':conversation-id="conversation.id"')
    expect(timeline).toContain('Citar mensagem')
    expect(timeline).toContain('message.source === \'FISCAL_AUTOMATION\'')
    expect(timeline).toContain('media === \'AUDIO\'')
    expect(timeline).toContain('download')
    expect(composer).toContain('emit(\'presence\', \'COMPOSING\')')
    expect(composer).toContain('emit(\'presence\', \'PAUSED\')')
    expect(composer).toContain('emit(\'presence\', \'RECORDING\')')
    expect(composer).toContain('MediaRecorder')
    expect(composer).toContain('shouldSubmitCommunicationComposer')
    expect(composer).toContain('kind: file.value ? fileKind.value : \'TEXT\'')
    expect(composer).toContain('ptt: Boolean(file.value && ptt.value)')
    expect(composer).toContain('accept="image/webp,.webp"')
  })

  it('prefetch visível prepara a timeline, deduplica requests e evita loading na troca', () => {
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    const page = source('app/components/communication/WorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const clearSelection = page.slice(
      page.indexOf('async function clearConversationSelection'),
      page.indexOf('async function closeMobileConversation')
    )
    expect(workspace).toContain('conversationDetails')
    expect(workspace).toContain('detailRequests')
    expect(workspace).toContain('initialTimelineRequests')
    expect(workspace).toContain('latestInitialTimelineRequest')
    expect(workspace).toContain('COMMUNICATION_PREFETCH_CONCURRENCY')
    expect(workspace).toContain('queueConversationPrefetch')
    expect(workspace).toContain('activeConversationPrefetchIds')
    expect(workspace).toContain('isLifecycleRequestCurrent')
    expect(workspace).toContain('isSynchronizationRequestCurrent')
    expect(workspace).toContain('selectionEpoch')
    expect(workspace).toContain('openingConversationId')
    expect(workspace).toContain('async function prefetchConversation')
    expect(workspace).toContain('if (epoch !== selectionEpoch) return false')
    expect(workspace).toContain('conversationDetails.value = {}')
    expect(workspace).toContain('async function refreshConversationDetail')
    expect(workspace).toContain('await refreshConversationDetail(selectedId, { reportError: false })')
    expect(page).toContain(':opening-id="workspace.openingConversationId.value"')
    expect(page).toContain('@prefetch="prefetchConversation"')
    expect(page).toContain('@prefetch-visible="prefetchVisibleConversations"')
    expect(list).toContain('@pointerenter="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain('@pointerdown="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain('@focus="emit(\'prefetch\', conversation.id)"')
    expect(list).toContain(':aria-busy="openingId === conversation.id"')
    expect(list).toContain('emit(\'prefetch-visible\', conversationIds)')
    expect(list).toContain('<USkeleton')
    expect(list).toContain('communication-conversations-skeleton')
    expect(timeline).toContain('timeline?.loading && !timeline.initialized')
    expect(page).toContain(':transition="false"')
    expect(page).not.toContain('scheduleMobileConversationFocusRestore(conversationId, 750)')
    expect(clearSelection).not.toContain('scheduleMobileConversationFocusRestore')
    expect(page).toMatch(/restoreConversationFocusAfterLeave[\s\S]+scheduleMobileConversationFocusRestore/)
    expect(page).toContain('conversationListRef.value?.focusList()')
    expect(workspace).toMatch(/initialized\.value = true\s+void synchronize\(\)/)
    expect(page).toContain('await syncRouteToSelection(workspace.selectedConversationId.value)')
  })

  it('carrega a timeline por cursor e confirma leitura somente após render visível', () => {
    const api = source('app/composables/api/createCommunicationApi.ts')
    const page = source('app/components/communication/WorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    const timelineUtils = source('app/utils/communication-timeline.ts')

    expect(api).toContain('include_messages?: boolean')
    expect(api).toContain('cursor?: string')
    expect(api).toContain('anchor?: \'latest\' | \'first_unread\'')
    expect(api).toContain('receipt_message_id?: number')
    expect(workspace).toContain('include_messages: false')
    expect(workspace).toContain('loadInitialConversationTimeline')
    expect(workspace).toContain('conversationTimelineGenerations')
    expect(workspace).toContain('isConversationTimelineRequestCurrent')
    expect(workspace).toContain('return loadConversationTimelinePage(id, \'newer\')')
    expect(workspace).toMatch(/const timelineReady = await loadInitialConversationTimeline\(id\)[\s\S]+selectedConversationId\.value = id/)
    expect(workspace).toContain('snapshot_through_message_id')
    expect(workspace).toContain('older_cursor')
    expect(workspace).toContain('newer_cursor')
    expect(workspace).toContain('acknowledgeConversationTimeline')
    expect(workspace).toContain('timelineReadAcknowledgementFailures')
    expect(workspace).toContain('receipt_message_id: receiptMessageId')
    expect(timelineUtils).toContain('shouldMarkCommunicationTimelineRead')
    expect(timeline).toContain('document.visibilityState === \'visible\'')
    expect(timeline).toContain('communication-timeline-load-older')
    expect(timeline).toContain('communication-timeline-load-newer')
    expect(timeline).toContain('timeline?.divider_message_id')
    expect(timeline).toContain('target.getBoundingClientRect()')
    expect(timeline).toContain('paginationRequestEpoch')
    expect(timeline).toContain('setTimeout(() => resetPagination(requestEpoch), 15_000)')
    expect(page).toContain('@load-older="loadOlderMessages"')
    expect(page).toContain('@load-newer="loadNewerMessages"')
    expect(page).toContain('@timeline-state="acknowledgeTimeline"')
    expect(page).toContain('parseCommunicationMessageId(route.params.messageId)')
    expect(page).toContain('routeMessageId.value')
    expect(page).toContain('selectConversationAtMessage(id, anchorMessageId)')
    expect(page).toContain('communicationConversationMessagePath')
    expect(page).not.toContain('route.query')
    expect(workspace).not.toContain('console.log(\'[Workspace]')
  })

  it('acompanha o fim condicionalmente e anuncia mensagens pendentes', () => {
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(timeline).toContain('appendedCommunicationMessages')
    expect(timeline).toContain('shouldFollowCommunicationTimeline')
    expect(timeline).toContain('followingLatest')
    expect(timeline).toContain('pendingNewMessages')
    expect(timeline).toContain('ResizeObserver')
    expect(timeline).toContain('@scroll.passive="handleMessagesScroll"')
    expect(timeline).toContain('communication-new-messages')
    expect(timeline).toContain('Ir para as mensagens mais recentes')
    expect(timeline).toContain('usePreferredReducedMotion')
  })

  it('representa tipos 1x1 e expõe somente ações tipadas do backend', () => {
    const content = source('app/components/communication/MessageContent.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const api = source('app/composables/api/createCommunicationApi.ts')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    for (const kind of ['LOCATION', 'CONTACT', 'POLL', 'INTERACTIVE', 'STICKER']) {
      expect(content).toContain(`message.kind === '${kind}'`)
    }
    expect(content).toContain('message.metadata?.revoked')
    expect(content).toContain('attachment.preview_url')
    expect(content).toContain('<audio')
    expect(content).toContain('<video')
    expect(content).toContain('markAudioPlayed')
    expect(timeline).toContain('message.metadata?.reactions')
    expect(timeline).toContain('COMMUNICATION_REACTION_EMOJIS')
    expect(timeline).toContain('scrollToMessage')
    expect(timeline).toContain('focusQuotedMessage')
    expect(timeline).toContain('title: \'Mensagem indisponível\'')
    expect(timeline).toContain('Editar mensagem')
    expect(timeline).toContain('Apagar para todos')
    expect(api).toContain('/messages/${messageId}/edit')
    expect(api).toContain('/messages/${messageId}/reaction')
    expect(api).toContain('/messages/${messageId}/poll-votes')
    expect(workspace).toContain('isCommunicationEphemeralEvent')
    expect(workspace).toContain('signalTimers')
    expect(workspace).toContain('const durable = incoming.filter')
  })

  it('compõe autorização de recovery com membership e inbox operacional', () => {
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const content = source('app/components/communication/MessageContent.vue')

    expect(timeline).toContain(':can-reply="canReply && outboundOperational"')
    expect(content).toContain('props.message.availability?.recoverable')
    expect(content).toContain('emit(\'recover\', message, \'MEDIA_RETRY\')')
    expect(content).not.toContain('emit(\'recover\', message, \'UNAVAILABLE\')')
  })

  it('mantém bolhas compactas, responsivas e acessíveis na timeline', () => {
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const content = source('app/components/communication/MessageContent.vue')
    expect(timeline).toContain('communication-message-bubble')
    expect(timeline).toContain('inline-block w-fit max-w-full')
    expect(timeline).toContain('max-w-[92%] sm:max-w-[78%] lg:max-w-[72%]')
    expect(timeline).toContain('\'rounded-br-md bg-primary/20 text-highlighted ring-primary/15\'')
    expect(timeline).toContain('\'-right-1 border-primary/15 bg-primary/20\'')
    expect(timeline).not.toContain('\'rounded-br-md bg-primary text-inverted ring-primary/30\'')
    expect(timeline).toContain('border-l-2 border-primary bg-default/50')
    expect(timeline).not.toContain('border-l-2 border-current')
    expect(timeline).toContain('\'rounded-bl-md bg-default text-highlighted ring-default\'')
    expect(timeline).toContain('\'rounded-bl-md bg-warning/10 text-highlighted ring-warning/40\'')
    expect(timeline).toContain('aria-hidden="true"')
    expect(timeline).toContain('Nota interna')
    expect(timeline).toContain('Enviada · WhatsApp')
    expect(timeline).toContain('Recebida · WhatsApp')
    expect(timeline).toContain('communication-message-meta')
    expect(timeline).toContain('<time :datetime="message.occurred_at || undefined">')
    expect(timeline).toContain('group-focus-within/message:opacity-100')
    expect(timeline).toContain('[@media(hover:hover)]:opacity-0')
    expect(timeline).toContain('aria-label="Reagir à mensagem"')
    expect(timeline).toContain('aria-label="Ações da mensagem"')
    expect(content).toContain('class="block w-full max-w-full px-2 py-2"')
    expect(content).not.toContain('min-w-56')
  })

  it('prioriza a identidade fiscal e mantém contato e telefone como contexto', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(list).toContain('communicationDisplayName(conversation)')
    expect(list).toContain('communicationListPhoneLine')
    expect(list).toContain('communication-conversation-secondary')
    expect(timeline).toContain(':title="communicationDisplayName(conversation)"')
    expect(timeline).toContain('communicationContactLabel(conversation)')
  })

  it('lista compacta expõe preview semântico, badge de não lidas e altura responsiva', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const page = source('app/components/communication/WorkspacePage.vue')
    const filters = source('app/components/communication/ConversationListFilters.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const communication = source('app/utils/communication.ts')
    const types = source('app/types/communication/conversations.ts')
    expect(types).toContain('last_message?: Message | null')
    expect(types).toContain('unread_count?: number')
    expect(types).toContain('preview?: ConversationPreview | null')
    expect(communication).toContain('communicationPreviewText')
    expect(communication).toContain('communicationPeerAddress')
    expect(communication).toContain('communicationListPhoneLine')
    expect(communication).toContain('communicationConversationImageEvidence')
    expect(list).toContain('communication-conversation-preview')
    expect(list).toContain('communication-conversation-unread')
    expect(list).toContain('ROW_HEIGHT_REM')
    expect(list).toContain('rowHeightPx')
    expect(list).toContain('getComputedStyle(document.documentElement).fontSize')
    expect(list).toContain('phoneLine(conversation)')
    expect(page).toContain('unreadOnly')
    expect(filters).toContain('communication-filter-unread')
    expect(timeline).toContain('communication-unread-divider')
    expect(timeline).toContain('first_unread_message_id')
  })

  it('expõe filtros operacionais, seleção bulk e preferências no workspace', () => {
    const page = source('app/components/communication/WorkspacePage.vue')
    const list = source('app/components/communication/ConversationList.vue')
    const filters = source('app/components/communication/ConversationListFilters.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const quickViews = source('app/utils/communication-conversation-quick-views.ts')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    const api = source('app/composables/api/createCommunicationApi.ts')
    const types = source('app/types/communication/conversations.ts')

    expect(types).toContain('ConversationSortBy')
    expect(types).toContain('BulkOperation')
    expect(types).toContain('ConversationListPreferences')
    expect(api).toContain('conversation-list-preferences')
    expect(api).toContain('conversation-bulk-operations')
    expect(api).toContain('Idempotency-Key')
    expect(api).toContain('label_ids')
    expect(api).toContain('sort_by')
    expect(workspace).toContain('selectedConversationIds')
    expect(workspace).toContain('selectAllLoadedConversations')
    expect(workspace).toContain('submitBulkOperation')
    expect(workspace).toContain('loadListPreferences')
    expect(workspace).toContain('clearOperationalSelection')
    expect(workspace).toContain('buildConversationBulkItems')
    expect(workspace).toContain('let bulkIdempotency')
    expect(workspace).toContain('const fingerprint = JSON.stringify({ action, params: params ?? null, items })')
    expect(workspace).toContain('bulkIdempotency?.fingerprint !== fingerprint')
    expect(workspace).toContain('bulkIdempotency.key')
    expect(page).toContain('communication-bulk-bar')
    expect(page).not.toContain('ShellBulkActionBar')
    expect(page).toContain('bulkActionMenus')
    expect(page).toContain(':data-testid="`communication-bulk-menu-${menu.key}`"')
    for (const [menuKey, align] of [
      ['read', 'start'],
      ['status', 'start'],
      ['more', 'end']
    ]) {
      expect(page).toMatch(new RegExp(`key: '${menuKey}',\\s+align: '${align}'`))
    }
    expect(page).toContain('align: menu.align')
    expect(page).toContain('communication-bulk-count')
    expect(page).toContain('communication-bulk-select-all')
    expect(page).toContain('communication-bulk-announcement')
    expect(page).toContain('aria-label="Ações em massa das conversas selecionadas"')
    expect(page).toMatch(/role="group"\s+aria-label="Ações em massa das conversas selecionadas"/)
    expect(page).toContain('communication-bulk-selection-label')
    expect(page).toContain('i-lucide-mail-check')
    expect(page).toContain('i-lucide-circle-fading-arrow-up')
    expect(page).toContain('i-lucide-ellipsis-vertical')
    expect(page).toContain('i-lucide-user-round-check')
    expect(page).toContain('i-lucide-list-tree')
    expect(page).toContain('i-lucide-tags')
    expect(page.match(/\.filter\(item => !item\.disabled\)/g)).toHaveLength(2)
    expect(page).toContain(':disabled="workspace.bulkSubmitting.value"')
    expect(page).not.toContain('absolute inset-x-2 bottom-2')
    expect(page).toMatch(/CommunicationConversationListFilters[\s\S]*#selection[\s\S]*communication-bulk-bar[\s\S]*CommunicationConversationList/)
    expect(filters).toContain('motion-reduce:transition-none')
    expect(page).toContain('clearBulkSelection')
    expect(list).not.toContain('pb-16 scroll-pb-16')
    expect(page).toContain('CommunicationConversationListFilters')
    expect(filters).toContain('communication-filter-view-${item.value.toLowerCase()}')
    expect(filters).toContain('<span class="sr-only">{{ item.ariaLabel }}</span>')
    expect(filters).toContain('[@media(pointer:coarse)]:pe-14')
    expect(quickViews).toContain('label: \'Em aberto\'')
    expect(quickViews).toContain('label: \'Não lidas\'')
    expect(quickViews).toContain('label: \'Não atribuídas\'')
    expect(quickViews).toContain('compactLabel: \'Não atrib.\'')
    expect(filters).not.toContain('ShellScrollableTabs')
    expect(filters).toContain('<UTabs')
    expect(filters).toMatch(/<UTabs[\s\S]{0,240}variant="pill"/)
    expect(filters).toContain('class="w-full min-w-0"')
    expect(filters).toContain('trigger: \'min-w-0 flex-1')
    expect(filters).toContain('<UFormField')
    expect(filters).toContain('<UChip')
    expect(filters).toContain('<UBadge')
    expect(filters.match(/<UPopover/g)).toHaveLength(2)
    expect(filters.match(/:portal="true"/g)).toHaveLength(2)
    expect(filters.match(/collisionPadding: 8/g)).toHaveLength(2)
    expect(filters).toMatch(/<UPopover[\s\S]{0,220}align: 'end'/)
    expect(filters).toMatch(/:open="advancedOpen"[\s\S]{0,220}align: 'start'/)
    expect(filters).not.toContain('<UModal')
    expect(filters).toContain('communication-filter-status-options')
    expect(filters).toContain('communication-filter-advanced-trigger')
    expect(filters).toContain('i-lucide-sliders-horizontal')
    expect(filters).toContain('i-lucide-list-filter')
    expect(filters).not.toContain('communication-filter-view-option-')
    expect(filters).toContain('quickViewTabs')
    expect(filters).toContain('activeQuickView')
    expect(filters).toContain('communication-filter-rule-add')
    expect(filters).toContain('communication-filter-rule-operator')
    expect(filters).toContain('communication-filter-advanced-incomplete')
    expect(filters).toContain('Todas as regras são combinadas com “E”.')
    expect(filters).toContain('Contém qualquer')
    expect(filters).toContain('max-w-[32rem]')
    expect(filters).toContain('overflow-x-hidden px-2 py-2')
    expect(filters).not.toContain('overflow-x-hidden px-3 py-2')
    expect(page).toContain('overflow-x-hidden border-b border-default px-0')
    expect(filters).toContain('communication-filter-active-summary')
    expect(filters).toContain('communication-filter-active-more')
    expect(filters).toContain('applyAdvancedFilters')
    expect(filters).toContain('resetAdvancedDraft')
    expect(filters).not.toContain('communication-filter-advanced-toggle')
    expect(filters).toContain('communication-filter-assignee')
    expect(filters).toContain('communication-filter-department')
    expect(filters).toContain('communication-filter-labels')
    expect(filters).toContain('communication-filter-sort')
    expect(filters).toContain('communication-filter-status')
    expect(page).toContain(':selection-active="workspace.selectedConversationCount.value > 0"')
    expect(page).toContain('@apply-quick-view="applyQuickView"')
    expect(page).toContain('function applyQuickView')
    expect(page).toContain('role="status"')
    expect(page).toContain('communication-realtime-status')
    expect(page).toContain('Atualização em tempo real: {{ COMMUNICATION_REALTIME_META[workspace.realtimeState.value].label }}')
    expect(page).toContain('data-testid="communication-bulk-announcement"')
    expect(page).toContain('communication-navbar-more')
    expect(list).toContain('<CommunicationConversationActions')
    expect(list).not.toContain('rowMenuItems')
    expect(timeline).toContain('<CommunicationConversationActions')
    expect(timeline).not.toContain('aria-label="Status da conversa"')
    expect(timeline).not.toContain('aria-label="Adiar conversa"')
    expect(page).toContain('@toggle-select')
    expect(page).not.toContain('@toggle-select-all')
    expect(page).toContain('ConversationActionPayload')
    expect(workspace).toContain('setConversationLabel')
    expect(workspace).toContain('useSurfaceNavigationState')
    expect(workspace).toContain('COMMUNICATION_SURFACES.workspace')
    for (const field of [
      'search',
      'inboxFilter',
      'statusFilter',
      'assigneeFilter',
      'departmentFilter',
      'unassignedOnly',
      'unreadOnly',
      'labelIdsFilter',
      'contactIdFilter',
      'sortBy'
    ]) {
      expect(workspace).toContain(`navigationState.state.value.${field}`)
    }
    expect(workspace).not.toContain('const search = ref(')
    expect(page).not.toContain('route.query')
  })

  it('contexto cobre operação, deep-link e privacidade gated por manage_contacts', () => {
    const context = source('app/components/communication/ContextPanel.vue')
    const page = source('app/components/communication/WorkspacePage.vue')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    expect(context).toContain('Responsável')
    expect(context).toContain('Fila / departamento')
    expect(context).toContain('Adiar conversa')
    expect(context).toContain('Marcadores')
    expect(context).toContain('Clientes vinculados')
    expect(context).toContain('Exportar contato')
    expect(context).toContain('Expurgar dados')
    expect(context).toContain('Mensagens temporárias')
    expect(context).toContain('signals?.contact?.available')
    expect(context).toContain('communication-context-close')
    expect(context).toContain('communicationContactPath')
    expect(context).toContain('communication-context-open-contact')
    expect(context).toContain('canManageContacts')
    expect(context).not.toContain('conversation.contact?.address ||')
    expect(context).toContain('resizable')
    expect(workspace).toContain('canManageCommunicationContacts as userCanManageCommunicationContacts')
    expect(workspace).toContain('const canManageContacts = computed')
    expect(page.match(/:can-manage-contacts="workspace\.canManageContacts\.value"/g)).toHaveLength(2)
    expect(page).toContain('if (!workspace.canManageContacts.value) return')
    expect(page).toContain('if (!workspace.canManageContacts.value || !purgeContactId.value) return')
  })

  it('administra switches, inbox, QR, membros, políticas e destinatários sem egress externo', () => {
    const admin = source('app/components/communication/AdministrationSlideover.vue')
    const inbox = source('app/components/communication/InboxAdminCard.vue')
    const policy = source('app/components/communication/AutomationPolicyCard.vue')
    const recipients = source('app/components/communication/RecipientConfigurationPanel.vue')
    expect(admin).toContain('defaults permanecem fail-closed')
    expect(admin).toContain('CommunicationInboxAdminCard')
    expect(admin).toContain('CommunicationAutomationPolicyCard')
    expect(admin).toContain('CommunicationRecipientConfigurationPanel')
    expect(inbox).toContain('QRCode.toDataURL')
    expect(inbox).toContain('Membros autorizados')
    expect(inbox).toContain('communicationSessionActions')
    expect(inbox).toContain('Ambiente com comunicação desativada')
    expect(inbox).toContain('Gateway do WhatsApp desativado')
    expect(inbox).toContain('Comunicação do escritório desativada')
    expect(inbox).toContain('Canal desativado')
    expect(inbox).toContain('Habilite o canal para usar “Conectar”.')
    expect(inbox).toContain('persistSettings')
    expect(policy).toContain('SKIPPED_NO_DOCUMENT')
    expect(policy).toContain('Inbox geral')
    expect(recipients).toContain('SELECTED')
    expect(inbox).not.toMatch(/https?:\/\//)
  })

  it('integra REST tenant-scoped e navegação permission-aware', () => {
    const api = source('app/composables/api/createCommunicationApi.ts')
    const navigation = source('app/utils/navigation.ts')
    const routes = source('app/utils/communication-routes.ts')
    expect(api).toContain('const base = \'/api/v1/communication\'')
    expect(api).toContain('/automation-recipients')
    expect(api).toContain('/events')
    expect(api).toContain('FormData')
    expect(navigation).toContain('id: \'communication\'')
    expect(navigation).toContain('COMMUNICATION_INDEX_PATH')
    expect(navigation).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(navigation).toContain('type: \'trigger\'')
    expect(navigation).toContain('canViewCommunication(user)')
    expect(routes).toContain('conversations/${id}')
    expect(routes).toContain('communicationConversationPath')
    expect(routes).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(source('app/pages/communication.vue')).toContain('CommunicationWorkspacePage')
    expect(source('app/pages/communication.vue')).toContain('isCommunicationWorkspacePath')
    expect(source('app/pages/communication/index.vue')).not.toContain('<CommunicationWorkspacePage')
    expect(source('app/pages/communication/conversations/[id].vue')).not.toContain('<CommunicationWorkspacePage')
    expect(source('app/components/communication/quick-responses/CatalogTable.vue')).toContain('ShellDataTable')
    expect(source('app/components/communication/CatalogAdminPanel.vue')).toContain('COMMUNICATION_QUICK_RESPONSES_PATH')
    expect(source('app/components/communication/CatalogAdminPanel.vue')).not.toContain('createCanned')
  })
})
